rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n

logger.ui.name = org.apache.spark.ui.SparkUI
logger.ui.level = info
logger.shell.name = org.apache.hadoop.util.Shell
logger.shell.level = error
logger.native.name = org.apache.hadoop.util.NativeCodeLoader
logger.native.level = error
logger.window.name = org.apache.spark.sql.execution.window
logger.window.level = error
logger.sparkenv.name = org.apache.spark.SparkEnv
logger.sparkenv.level = error
