<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pe.edu.vallegrande</groupId>
        <artifactId>spark</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>spark-academico</artifactId>
    <name>Spark Academico - Bronze y Silver</name>

    <dependencies>
        <dependency>
            <groupId>pe.edu.vallegrande</groupId>
            <artifactId>spark-core</artifactId>
        </dependency>
    </dependencies>
</project>
